version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "key-log-redis"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-135zhihkdzt7i"
s3_prefix = "key-log-redis"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
