AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  redis_crud

  Sample SAM Template for redis_crud

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.8
    Timeout: 30
    Layers:
      - !Ref RedisProxyLayer
      - !Ref RedisHttpLayer
    Environment:
      Variables:
        API_URI: https://pu65bkndtvahlfy5nvhs5vzuhq.appsync-api.us-west-2.amazonaws.com/graphql
        API_KEY: da2-scoukebkyzcbrd5mwc7zswe7bm
Resources:
  RedisProxyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: python_redis_proxy_layer/python
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8    

  RedisHttpLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: go_redis_ipc_extension_layer/bin/extension.zip
      CompatibleRuntimes:
        - go1.x

  RedisCRUD:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: redis_crud
      Handler: app.lambda_handler
      Policies:
        - AWSLambda_FullAccess
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Method: POST
            Path: /redis_crud
          CorsConfiguration:
            AllowOrigins:
              - "*"
            AllowHeaders:
              - x-apigateway-header
            AllowMethods:
              - POST
              - GET

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  RedisCRUD:
    Description: "Redis CRUD Function URI"
    Value: !Sub "http://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/redis_crud"

